### ISSUE TITLE
RandomDateTimeGenerator generate ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by lwuckel** [PawelSienko/Randomizer.NET#1]
I get folloing issue

System.ArgumentOutOfRangeException : Year, Month, and Day parameters describe an un-representable DateTime.
  Stapelüberwachung: 
    DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
    DateTime.ctor(Int32 year, Int32 month, Int32 day)
    RandomDateTimeGenerator.GenerateValue()

**Comment by PawelSienko** [comment]
Hi,

please provide reproduction steps to reproduce an issue.

**Comment by lwuckel** [comment]
To reproduce this issue is not so easy while using random values.
But the problem is the implementation

You get the error message if you generate a date like 31.2.2020
new DateTime(2020, 2, 31);

**Comment by PawelSienko** [comment]
Thank you for reproduction steps. I will push a new version with fix of this issue.

**Comment by PawelSienko** [comment]
The issue has been resolved. Please update to newest version 2.2.28.
